Unit tests for the http library
taktik/typescript-http-client pull request #4
Opened 2019-03-26 10:50 UTC by IamVanilla

Comments are very basic, but they do help me find myself

Tested all the methods I could, before running in the export problem of the execute method. Committing in prevision of splitting the index.ts file in at least two different files to ease the reading and the implementation of tests

2019-03-26 11:07 UTC, hubjac1 commented
Thanks IamVanilla, 

I add few comments. 
In addition, Could you check tslint and code coverage?

2019-03-26 11:08 UTC, hubjac1 requested changes

2019-03-26 11:08 UTC, hubjac1 commented on README.md
> +In the tests, you need to first in indicate which name space you are testing, and then precise which method. Both using describe. The entity tested is the first argument of describe.
Those lines (7 -10) are not specific to this project, so you don't need to add then in the readme. 
But it would be useful to describe in short the  purpose of this project.

2019-03-26 11:08 UTC, hubjac1 commented on package.json
> +		"@types/node": "^11.11.6",
why do you need this?

2019-03-26 11:08 UTC, hubjac1 commented on src/index.ts
> +			// Creating an xmlhttprequest and giving it two proprities
properties

2019-03-26 11:08 UTC, hubjac1 commented on test/e2e/test-basic.ts
> +  //Initializing all variables that we will need
declaring all variables that we will need

2019-03-26 11:08 UTC, hubjac1 commented on test/e2e/test-basic.ts
> +  // describe('what to describe', function() {
cloud you add a test to verify that filters are actually called on the response?

2019-03-26 14:35 UTC, antoinebaudoux commented on README.md
> +In the tests, you need to first in indicate which name space you are testing, and then precise which method. Both using describe. The entity tested is the first argument of describe.
Yes, this is too specific to be in the main readme. You should at least put this in a "testing" section

2019-03-26 14:36 UTC, antoinebaudoux commented on karma.conf.js
> +    browsers: ['ChromeHeadless'], //['PhantomJS'],
Are we definitively switching to ChromeHeadless? If so, you can remove the PhantomJS part

2019-03-26 14:38 UTC, antoinebaudoux commented on src/index.ts
> +		// Takes parameteres and created an InstalledFilter with them
Spelling

2019-03-26 14:40 UTC, antoinebaudoux commented on src/index.ts
> +		// Takes a Request and returns the body of the method callForResponse with the same parameter
It doesn't return the body of the method `callForResponse` method, it returns the body of the Response object returned by `callForResponse`

2019-03-26 14:41 UTC, antoinebaudoux commented on src/index.ts
> +		// Takes a Request, creates a FilterChainChamp with the current filters and then calls the method doFilter with the received Request
Spelling

2019-03-26 14:41 UTC, antoinebaudoux commented on src/index.ts
> +	// Interfaces can hold proprities, this interface only contains a map of string-string
Spelling

2019-03-26 14:41 UTC, antoinebaudoux commented on src/index.ts
> +	// Contains every parameter needed for a request as proprities
Spelling

2019-03-26 14:41 UTC, antoinebaudoux commented on src/index.ts
> +		// A way to decalre an enumeration (can be anything because of the string but the IDE will suggest the 4 first verbs)
Spelling

2019-03-26 14:42 UTC, antoinebaudoux commented on src/index.ts
> +		// sets the proprities (like a constructor for changes)
Spelling

2019-03-26 14:43 UTC, antoinebaudoux commented on src/index.ts
> +			// Initilizes the request
Spelling

2019-03-26 14:46 UTC, antoinebaudoux commented on test/e2e/test-basic.ts
> +		it('should change all the proprities of a Request', function() {
Spelling

2019-03-26 14:49 UTC, antoinebaudoux commented on test/e2e/test-basic.ts
> +		// Test successful only if each proprety has changed
Spelling

2019-03-26 14:51 UTC, antoinebaudoux requested changes
Thanks for the PR. Please correct various problems before merge

2019-03-28 09:55 UTC, IamVanilla commented on src/index.ts
> +		// A way to decalre an enumeration (can be anything because of the string but the IDE will suggest the 4 first verbs)
I don't see it :(

2019-04-01 12:06 UTC, antoinebaudoux commented on src/index.ts
> +		// A way to decalre an enumeration (can be anything because of the string but the IDE will suggest the 4 first verbs)
"decalre" -> "declare"

2019-04-01 12:14 UTC, antoinebaudoux requested changes
Typos to fix + comment to clarify

2019-04-01 12:14 UTC, antoinebaudoux commented on src/index.ts
> +	 * Interface usefull to remove a Filter after it has been added to the httpCLient array
useful

2019-04-01 12:14 UTC, antoinebaudoux commented on src/index.ts
> +	 * Interface usefull to remove a Filter after it has been added to the httpCLient array
httpClient

2019-04-01 12:14 UTC, antoinebaudoux commented on src/index.ts
> +	 * Interface that oblige the object to have a method that takes a request and returns a response,
I don't understand what you mean by that comment. Could you clarify?

2019-04-01 12:14 UTC, antoinebaudoux commented on src/index.ts
> +		 * nested filters. So it contains an array of filter and its doFilter loops trhought all its filters
typo "trhought"

2019-04-01 15:51 UTC, antoinebaudoux approved these changes

2019-04-01 15:51 UTC, merged