Unit tests
taktik/typescript-http-client pull request #5
Opened 2019-04-10 12:08 UTC by IamVanilla

I finished unit tests for the library

2019-04-10 13:11 UTC, hubjac1 commented
Good job, I left a few comments.

2019-04-10 14:03 UTC, hubjac1 commented on .nyc_output/1cbd51b1-47e0-4420-aa9c-83e9ada0dfba.json
> +{}
remove this file

2019-04-10 14:03 UTC, hubjac1 commented on .nyc_output/517f1366-34dd-40db-8e02-35d0dbc4a478.json
> +{}
remove this file

2019-04-10 14:03 UTC, hubjac1 commented on package.json
> +		"tescov": "nyc mocha"
remove this command

2019-04-10 14:03 UTC, hubjac1 commented on package.json
> +		"nyc": "^13.3.0",
useless dependency

2019-04-10 14:03 UTC, hubjac1 commented on test/test-basic.ts
>  			assert.notEqual(aRequest.timeout, 30000)
I's better to test it the properties are equal to the new value

2019-04-10 14:03 UTC, hubjac1 commented on test/test-basic.ts
> +			assert.equal((theResponse.request.body as Post).body, '(╯°□°）╯︵ ┻━┻')
😄

2019-04-10 14:03 UTC, hubjac1 commented on test/test-unitaires-execute.ts
> +				'salary': '333',
333k

2019-04-10 14:03 UTC, hubjac1 commented on test/test-unitaires-execute.ts
> +		it('should also throw an error', async function() {
could you be more descriptive?

2019-04-17 09:26 UTC, antoinebaudoux requested changes

2019-04-17 09:26 UTC, antoinebaudoux commented on src/execute.ts
> +		// This inernal method takes an XMLHttpRequest and will return a Response
Typo "inernal"

2019-04-19 07:38 UTC, antoinebaudoux approved these changes

2019-04-19 07:38 UTC, merged